[HEADER]
original_input_filename=/media/SSD_4TB/TB11/raw/Run8_DCsquare_500um_new_board1_tracker8_140V_20C_HG.root
output_filename=/media/SSD_4TB/TB11/stats/stats_Run8_tracks.root
#output_filename=/media/SSD_4TB/TB11/stats/prova.root


[CHANNELS]
active_channels=17
ch_mcp = 0

[RANGES]
# if ==1, the signals are searched in the interval defined by pmax_search_range
search_range=1
pmax_search_range_min=10
pmax_search_range_max=190
# if ==1, the signals are searched in a time window centered around the channel that recorded the highest signal. The signals of ch_mcp are excluded from this type of search. The time interval of small_range is defined as +/- small_range_interval
small_range=0
# if ==1, the signals are searched in a time window centered around the peak time of ch_mcp; the time interval is defined as +/- mcp_range_interval. Note: either set small_range or mcp_range to 1.
mcp_range=0
small_range_interval = 1
# default mcp_range_interval : 1.5
mcp_range_interval = 3

[PARAMETERS]
# max number of samples to be used in the gaus fit used to compute the Pmax. Default is 7. Ther algorithm tries this value, if it fails, it tries with number_points_gaus_fit-2; if it is still failing, take the max sampled values and set the chi2 to -10000 
number_points_gaus_fit=7
# ==1 when using the digitizer. The conversion factor is used for ADC --> V. The temporal bin width is the sampled time interval of the digitizer in ns (default 0.2 ns) 
ADC_conversion=1
ADC_conversion_factor=0.25
temporal_bin_width=0.2
# =1 gives signals in mV; adjust accordingly if you want a different value
voltage_scalar=1
# =1 gives signals in ns; adjust accordingly if you want a different value
time_scalar=1
sampling_points=1020
# the first n_points_baseline are used to compute the RMS noise ans baseline subtraction
n_points_baseline=20
tot_rising=5
tot_falling=5
# temporal distance between DUT and MCP/ trigger/ time reference
# run 100: 3.5
# run 400: 2.8
# run 600: 3.5
mcp_delay=4
# number of threads for parallel processing (0 = use all available cores, 8=super safe, 12=safe, 16=performance)
n_threads=16
# maximum number of events to process (0 = no limit, useful for quick tests)
max_events=700000


[TRACKER]
# if you are adding tracker position to the final root file 
join_txt_tracker = 1
# if tracker position are taken from an txt/csv file
tracker_filename=/media/SSD_4TB/TB11/telescope_txt/run8.csv
# event offset between digitizer and tracker (0 = ADENIUM, 1 = MIMOSA)
tracker_offset = 0

[ACTIVE_CHANNEL]
ch0=1
ch1=1
ch2=1
ch3=1
ch4=1
ch5=1
ch6=1
ch7=1
ch8=1
ch9=1
ch10=1
ch11=1
ch12=1
ch13=1
ch14=1
ch15=1
ch16=1
trg0=1
trg1=1

[INVERT_SIGNAL]
ch0=1
ch1=1
ch2=1
ch3=1
ch4=1
ch5=1
ch6=1
ch7=1
ch8=1
ch9=1
ch10=1
ch11=1
ch12=1
ch13=1
ch14=1
ch15=1
ch16=1
trg0=0
trg1=0
