[HEADER]
input_filename=/Users/icosivi/Desktop/ETL_SPS_May25/raw/Sr_Run1_Ch0-500V_Ch1-500V_Ch2-300V_Ch3-190V_trig5V.root
output_filename=/Users/icosivi/Desktop/ETL_SPS_May25/stats/stats_Sr_Run1_Ch0-500V_Ch1-500V_Ch2-300V_Ch3-190V_trig5V.root


[CHANNELS]
active_channels=8

[RANGES]
# if ==1, the signals are searched in the interval defined by pmax_search_range
search_range=1
pmax_search_range_min=-80e-9
pmax_search_range_max=80e-9

[PARAMETERS]
# max number of samples to be used in the gaus fit used to compute the Pmax. Default is 7. Ther algorithm tries this value, if it fails, it tries with number_points_gaus_fit-2; if it is still failing, take the max sampled values and set the chi2 to -10000 
number_points_gaus_fit=7
# =1 gives signals in mV; adjust accordingly if you want a different value
voltage_scalar=1000
# =1 gives signals in ns; adjust accordingly if you want a different value
time_scalar=1e9
sampling_points=950
# the first n_points_baseline are used to compute the RMS noise ans baseline subtraction
n_points_baseline=50
tot_rising=0.05
tot_falling=0.05


[TRACKER]
# if you are adding tracker position to the final root file 
join_txt_tracker = 1
# if tracker position are taken from an txt/csv file
tracker_filename=


[ACTIVE_CHANNEL]
ch0=1
ch1=1
ch2=1
ch3=1
ch4=1
ch5=1
ch6=1
ch7=1
ch8=1
ch9=1
ch10=1
ch11=1
ch12=1
ch13=1
ch14=1
ch15=1
trg0=1
trg1=1

[INVERT_SIGNAL]
ch0=1
ch1=1
ch2=1
ch3=1
ch4=1
ch5=1
ch6=1
ch7=1
ch8=1
ch9=1
ch10=1
ch11=1
ch12=1
ch13=1
ch14=1
ch15=1
trg0=0
trg1=0

[PS]
ps_channel0=1
ps_channel1=1
ps_channel2=1
ps_channel3=1
